# Generated by Django 5.1.2 on 2024-11-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognized_id', models.CharField(max_length=100)),
                ('recognized_name', models.CharField(max_length=255)),
                ('recognition_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
