# Generated by Django 5.1.2 on 2024-11-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognize', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdNameMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
